site_name: TMIP-EMAT + VisionEval
docs_dir: content
repo_url: http://github.com/driftlesslabs/EMAT_VE
repo_name: driftlesslabs/EMAT_VE
theme:
  name: material
  palette:
    primary: blue
    accent: deep orange
  features:
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: "../../.."
  - pymdownx.superfences

plugins:
  - search
  - markdown-exec
